[package]
name = "sqlparser-test-pass"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sqlparser = "0.54.0"
tokio.workspace = true
serde_json.workspace = true
serde.workspace = true
csv = "1.2"
